# Generated by Django 4.2.6 on 2023-11-20 15:52

import apps.car_rental.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.car_rental.utils.files.car_storage, validators=[apps.car_rental.utils.files.validate_image_extension, apps.car_rental.utils.files.max_file_size_validator]),
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profiles/default.jpg', null=True, upload_to=apps.car_rental.utils.files.customer_storage, validators=[apps.car_rental.utils.files.validate_image_extension, apps.car_rental.utils.files.max_file_size_validator]),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to=apps.car_rental.utils.files.payment_storage, validators=[apps.car_rental.utils.files.validate_image_extension, apps.car_rental.utils.files.max_file_size_validator]),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagent',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profiles/default.jpg', null=True, upload_to=apps.car_rental.utils.files.agent_storage, validators=[apps.car_rental.utils.files.validate_image_extension, apps.car_rental.utils.files.max_file_size_validator]),
        ),
        migrations.AddField(
            model_name='rentalagent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
