# Generated by Django 4.2.6 on 2024-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_car_price_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number_plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
